# -*- coding: utf-8 -*-
"""PysparkSetupOnColab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OdAJnwY2fND7xPXJ8x7DlsFqaFgFB_88
"""

!pwd
!ls
!python --version

#!wget https://mirrors.estointernet.in/apache/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
!wget https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz
!tar -xvzf spark-3.0.0-bin-hadoop2.7.tgz
!pip install findspark

import os
os.environ["SPARK_HOME"] = "/content/spark-3.0.0-bin-hadoop2.7"
import findspark
findspark.init()

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("Create DataFrame from CSV File in PySpark 3.0").getOrCreate()
print(spark.sparkContext.appName)

